---
title: "intro"
runtime: shiny
output: html_document
---

## How this App works

Inspired by the **WorldCupBook** of the Twitter Tipsters @InplayMan, @cornersbychris and @HouseOfCardsTip, I was thinking about how to get all these stats collected and automatically updated with the newest results. @InPlayMan offers his great MegaStatPack, but it's not easy to use if you search for teams or if you want to sort data. So I decided to write my own application using **R Shiny**. Since I would love to have some feedback (@iLoveSportsData), I'll invest to run it on a public server instead of only running it locally. Some detailed information about the app:

1. Data come from http://football-data.co.uk and are updated regularly after game days. Many thanks to @12Xpert for his great work.

2. Currently, data about goals, cards, corners and referees are included. You'll find averages and share of games with a certain number of goals, cards or corners. 

3. The Data cover only league games, so there is limited value for international or cup games.

4. Data can be searched by League and/or teams and playing site (all, home, away). Also, there is an extra section about referees, which can be selected in the dropdown menu. Sorting is possible in order to search for lowest/highest values.

5. Data for goals, cards and corners are only collected for current season, since historical data are not relevant for sports betting in my opinion. Data about referees include current and previous season, since the referees style is not likely to change.

6. By now, data include the following leagues:

* England: Premier League, Championship, League One, League Two, National League.
* Scotland: Premiership, Championship, League One, League Two.
* Germany: Bundesliga, 2. Bundesliga.
* Italy: Serie A, Serie B.
* Spain: La Liga, La Liga 2.
* France: Ligue 1, Ligue 2.
* Netherlands: Eredivisie.
* Belgium: Jupiler League.
* Portugal: Primeira Liga.
* Turkey: Super Lig.
* Greece: Super League.

  Data about referees cover only England and Scotland.
  
As already written at the beginning, I want to share this app in order to see if it is helpful also for others and also in order to improve it. For the future, I have some possible additions on my list:

* add other leagues, where data are available on http://football-data.co.uk.
* add historical data (not for betting, but to be more complete).
* add a collection for tennis data, which are publicly available (e.g. http://tennis-data.co.uk/).

